#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Local CI runner for adrpadua/webgame"

REPO_URL="https://github.com/adrpadua/webgame"
RUNNER_LABEL="playwright"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — what this machine is"
say "The browser smoke suite needs a real Chromium. Rather than install one"
say "inside every CI job — which is what used to wedge on apt-get — this"
say "machine gets one, once, and keeps it."
printf '\n'
OS_NAME="$(uname -s)"
ARCH_NAME="$(uname -m)"
case "$OS_NAME" in
  Linux)  RUNNER_OS="linux" ;;
  Darwin) RUNNER_OS="osx" ;;
  *) warn "Unsupported OS: $OS_NAME. The runner supports Linux and macOS."; exit 1 ;;
esac
case "$ARCH_NAME" in
  x86_64|amd64) RUNNER_ARCH="x64" ;;
  arm64|aarch64) RUNNER_ARCH="arm64" ;;
  *) warn "Unsupported architecture: $ARCH_NAME."; exit 1 ;;
esac
step "OS/arch:   $RUNNER_OS-$RUNNER_ARCH"
if command -v node >/dev/null 2>&1; then
  step "Node:      $(node -v)"
else
  warn "Node is not on PATH. Install Node 22+ before running this."
  exit 1
fi
say ""
ask RUNNER_DIR "Where should the runner live? [\$HOME/actions-runner]"
[[ -z "$RUNNER_DIR" ]] && RUNNER_DIR="$HOME/actions-runner"
ask RUNNER_NAME "Name this runner [$(hostname -s 2>/dev/null || echo webgame-local)]"
[[ -z "$RUNNER_NAME" ]] && RUNNER_NAME="$(hostname -s 2>/dev/null || echo webgame-local)"
note "runner dir:  $RUNNER_DIR"
note "runner name: $RUNNER_NAME"
note "label:       $RUNNER_LABEL  (the workflow targets this)"
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Download the runner"
say "Fetching the latest actions/runner release for $RUNNER_OS-$RUNNER_ARCH."
if [[ -x "$RUNNER_DIR/config.sh" ]]; then
  note "A runner is already unpacked at $RUNNER_DIR — skipping the download."
else
  mkdir -p "$RUNNER_DIR"
  RUNNER_VERSION="$(curl -fsSL https://api.github.com/repos/actions/runner/releases/latest \
    | grep -m1 '"tag_name"' | sed -E 's/.*"v?([^"]+)".*/\1/')"
  if [[ -z "$RUNNER_VERSION" ]]; then
    warn "Could not read the latest runner version from the GitHub API."
    warn "Check https://github.com/actions/runner/releases and unpack it into $RUNNER_DIR by hand."
    exit 1
  fi
  TARBALL="actions-runner-${RUNNER_OS}-${RUNNER_ARCH}-${RUNNER_VERSION}.tar.gz"
  step "version $RUNNER_VERSION"
  curl -fsSL -o "$RUNNER_DIR/$TARBALL" \
    "https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/${TARBALL}"
  tar xzf "$RUNNER_DIR/$TARBALL" -C "$RUNNER_DIR"
  rm -f "$RUNNER_DIR/$TARBALL"
  printf '  %s✓%s unpacked into %s\n' "$GREEN" "$RESET" "$RUNNER_DIR"
fi
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Registration token"
say "A runner registers with a short-lived token that only you can mint."
say "It expires about an hour after it is shown, so grab it now."
open_url "${REPO_URL}/settings/actions/runners/new?arch=${RUNNER_ARCH}&os=${RUNNER_OS}"
step "On that page, find the 'Configure' box."
step "Copy the token after '--token' (it starts with A and is ~29 characters)."
note "Nothing is written to disk — the token is used once, here."
ask_secret RUNNER_TOKEN "Paste the registration token:"
if [[ -z "$RUNNER_TOKEN" ]]; then
  warn "No token entered. Re-run once you have one."
  exit 1
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Register the runner"
say "Registering '$RUNNER_NAME' with the label '$RUNNER_LABEL'."
if [[ -f "$RUNNER_DIR/.runner" ]]; then
  note "This runner is already configured."
  if confirm "Remove the old registration and configure it again?"; then
    ( cd "$RUNNER_DIR" && ./config.sh remove --token "$RUNNER_TOKEN" ) || \
      warn "Removal failed — continuing; the token may already be spent."
  else
    note "Keeping the existing registration."
  fi
fi
if [[ ! -f "$RUNNER_DIR/.runner" ]]; then
  ( cd "$RUNNER_DIR" && ./config.sh \
      --url "$REPO_URL" \
      --token "$RUNNER_TOKEN" \
      --name "$RUNNER_NAME" \
      --labels "$RUNNER_LABEL" \
      --unattended --replace )
  printf '  %s✓%s registered\n' "$GREEN" "$RESET"
fi
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Bake Chromium into this machine"
say "This is the whole point: the browser is installed once, now, so no CI"
say "job ever shells out to apt-get again."
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
step "Installing dependencies in $REPO_ROOT/web"
( cd "$REPO_ROOT/web" && npm ci )
if [[ "$RUNNER_OS" == "linux" ]]; then
  say ""
  warn "The next command needs sudo: Playwright installs system libraries."
  note "On macOS it needs none, and this step runs unprivileged."
  pause "Press Enter to run it"
  ( cd "$REPO_ROOT/web" && npx playwright install --with-deps chromium )
else
  ( cd "$REPO_ROOT/web" && npx playwright install chromium )
fi
printf '  %s✓%s Chromium is on this machine and cached for every future job\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Run it as a service"
say "As a service the runner survives logout and reboot, and picks up jobs"
say "without a terminal left open."
if confirm "Install and start the runner as a background service?"; then
  if [[ "$RUNNER_OS" == "linux" ]]; then
    ( cd "$RUNNER_DIR" && sudo ./svc.sh install "$(whoami)" && sudo ./svc.sh start )
  else
    ( cd "$RUNNER_DIR" && ./svc.sh install && ./svc.sh start )
  fi
  printf '  %s✓%s service started\n' "$GREEN" "$RESET"
  note "Stop it later with: cd $RUNNER_DIR && sudo ./svc.sh stop"
else
  SKIPPED+=("run the runner: cd $RUNNER_DIR && ./run.sh")
  note "Skipped. Start it by hand with: cd $RUNNER_DIR && ./run.sh"
fi
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Close the fork door"
warn "adrpadua/webgame is a PUBLIC repository."
say ""
say "A self-hosted runner runs jobs on THIS machine. On a public repo, anyone"
say "can open a pull request from a fork, and without a guard that pull"
say "request's workflow would execute their code here."
say ""
say "The workflow already refuses to run the smoke job for a pull request"
say "from a fork, so this is defence in depth rather than the only lock —"
say "but set it anyway, because the guard is one line someone could delete."
open_url "${REPO_URL}/settings/actions"
step "Find 'Fork pull request workflows from outside collaborators'."
step "Select 'Require approval for all outside collaborators'."
step "Click Save."
pause "Press Enter once that is saved"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Verify, and switch the job on"
say "The runner should now be listed and Idle."
open_url "${REPO_URL}/settings/actions/runners"
step "Confirm '$RUNNER_NAME' is listed, green, and Idle."
step "Check it carries the '$RUNNER_LABEL' label."
pause "Press Enter once you can see it"
say ""
say "Last thing: the smoke job asks whether a runner is supposed to exist"
say "before it requests one, because a job whose labels match nothing sits"
say "queued for 24 hours rather than failing fast. Setting this switches it on."
set_var SELF_HOSTED_SMOKE true
note "Unset it later if this machine goes away: gh variable delete SELF_HOSTED_SMOKE"
say ""
say "The next pull request runs the smoke suite here. To try it now, push a"
say "branch and open one — or run the local gate directly:"
note "  cd $REPO_ROOT/web && npm run verify:local"
pause "Press Enter to finish"

finish
