#!/usr/bin/env python3
"""Build the Oathcraft Design System bundle for Claude Design.

Emits the file layout a Claude Design *design-system* project expects:

    colors_and_type.css     the system stylesheet — tokens, plates, components
    preview/*.html          one card per concept, each opening with @dsCard
    _ds_manifest.json       the card index and token table the pane reads
    README.md               what this is and where every value came from

Two rules hold the whole thing together:

  1. Nothing here is authored twice. The tokens come from
     `design/oathcraft_tokens.py`; the component renderers and the plate CSS
     are imported from the canvas builder next door, which already ports them
     faithfully from `web/src/`. A card is a caption around a real component.
  2. No prose is carried by copy. An earlier version shipped three canon docs
     as verbatim copies, and one of them was stale on arrival — it asserted a
     board palette collision the code had already resolved, and said so to
     anyone reading the design language cold. The cards carry the reasoning
     that matters at the point of use; everything else links to the repo
     (D-068).

Run from the repo root:  python3 design/design-system/build_ds.py
"""

import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DESIGN = os.path.dirname(HERE)
sys.path.insert(0, DESIGN)

import oathcraft_tokens as T  # noqa: E402

# The canvas builder already ports every component from `web/src/` — reuse it
# rather than writing a second, drifting copy.
_spec = importlib.util.spec_from_file_location("canvas_build", os.path.join(DESIGN, "current-game-ui", "build.py"))
canvas = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(canvas)

OUT = HERE
CARDS = []


# --- The system stylesheet -------------------------------------------------
def stylesheet():
    return f"""/* The Oathcraft design system.
 *
 * Generated by design/design-system/build_ds.py from design/oathcraft_tokens.py.
 * The shipped source of truth is web/src/index.css; this file is that system
 * restated for Claude Design. Do not hand-edit — regenerate.
 *
 * The material language, the plate geometry and the review checklist are
 * specified in docs/content/oathcraft-interface-direction.md.
 */
:root {{
{T.tokens_css()}
}}

{canvas.BASE_CSS}
{canvas.PLATE_CSS}
{canvas.TRACK_CSS}
{canvas.BAR_CSS}
{canvas.HAND_CSS}
{canvas.FRAME_CSS}
{canvas.STATUS_CSS}
{canvas.PARTY_CSS}
{canvas.DOCK_CSS}

/* --- Preview chrome ------------------------------------------------------
   Every preview sits on this, so the pane reads as one system rather than as
   twenty differently-padded screenshots.

   Namespaced `ds-`, because the component classes above it are the real ones,
   shared with the canvas builder, and `.card` is already the Compact Card. The
   collision crushed every hand card on a preview to 45px of content before the
   overrun check caught it. */
html, body {{ margin: 0; background: transparent; color: var(--fg-primary); font-family: var(--font-sans); }}
.ds-card {{
  padding: 18px 22px; display: flex; flex-direction: column; gap: 12px;
  background: var(--surface); border: 1px solid var(--steel-800); border-radius: 14px;
}}
.ds-lbl {{
  font-size: var(--type-chip); letter-spacing: var(--tracking-widest);
  text-transform: uppercase; color: var(--fg-quiet);
}}
.ds-note {{ font-size: 11px; line-height: 1.55; color: var(--steel-400); }}
.ds-note b {{ color: var(--ceramic-300); font-weight: 600; }}
.ds-warn {{
  font-size: 11px; line-height: 1.5; color: var(--gold-200);
  border-left: 3px solid var(--gold-500); padding-left: 10px;
}}
.ds-grid {{ display: flex; flex-wrap: wrap; gap: 10px; }}
.ds-stack {{ display: flex; flex-direction: column; gap: 10px; }}
.ds-swatch {{ display: flex; flex-direction: column; gap: 4px; }}
.ds-chipbox {{ width: 74px; height: 44px; border-radius: 3px; border: 1px solid rgba(255,255,255,.07); }}
.ds-mono {{ font-family: var(--font-mono); font-size: 10px; color: var(--steel-400); }}
.ds-name {{ font-size: 11px; font-weight: 600; color: var(--ceramic-300); }}
.ds-demo {{ background: linear-gradient(180deg,#131c2b,#0b1220); border-radius: 6px; padding: 12px; }}
"""


# --- Card shell ------------------------------------------------------------
def card(path, group, name, subtitle, body, extra_css="", width=560):
    """One preview card. The @dsCard marker MUST be the first line — the pane
    builds its index from it."""
    CARDS.append({"path": f"preview/{path}", "group": group, "subtitle": subtitle, "name": name})
    html = f"""<!-- @dsCard group="{group}" name="{name}" subtitle="{subtitle}" -->
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="../colors_and_type.css" />
    <style>
      .ds-card {{ width: {width}px; }}
      {extra_css}
    </style>
  </head>
  <body>
    <div class="ds-card">{body}</div>
  </body>
</html>
"""
    write(os.path.join("preview", path), html)


def write(rel, text):
    full = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as handle:
        handle.write(text)


# --- Colour cards ----------------------------------------------------------
def ramp_card(material, stem, carries, ramp, anchor, subtitle, extra=""):
    swatches = "".join(
        f'<div class="ds-swatch"><div class="ds-chipbox" style="background:{ramp[s]}'
        f'{";box-shadow:0 0 0 2px var(--gold-400)" if s == anchor else ""}"></div>'
        f'<div class="ds-name">{stem}-{s}{" ·" if s == anchor else ""}</div>'
        f'<div class="ds-mono">{ramp[s].upper()}</div></div>'
        for s in sorted(ramp)
    )
    body = (
        f'<div class="ds-lbl">{material} — {carries}</div>'
        f'<div class="ds-grid">{swatches}</div>'
        f'<div class="ds-note">The gold-ringed step is the interface direction\'s own hex; the rest are what '
        f'that material looks like lit, dim, or as a dark ground. <b>A material picks its step from the '
        f'ground it sits on</b> — the ramp exists so it can, not so a designer can pick a nicer blue.</div>'
        f'{extra}'
    )
    card(f"colors-{stem}.html", "Colors", material, subtitle, body)


def colour_cards():
    table = "".join(
        f'<tr><td style="padding:5px 12px 5px 0"><span class="ds-chipbox" style="width:26px;height:16px;'
        f'display:inline-block;vertical-align:middle;background:{ramp[anchor]}"></span></td>'
        f'<td style="padding:5px 12px 5px 0" class="ds-name">{material}</td>'
        f'<td style="padding:5px 12px 5px 0" class="ds-mono">{ramp[anchor].upper()}</td>'
        f'<td style="padding:5px 0" class="ds-note">{carries}</td></tr>'
        for material, stem, carries, ramp, anchor in T.PALETTE
    )
    body = (
        '<div class="ds-lbl">The locked table</div>'
        f'<table style="border-collapse:collapse;width:100%">{table}</table>'
        '<div class="ds-note"><b>Colour reads as role and material, never as decoration.</b> If a new colour is '
        'needed, the answer is almost always that the wrong material was chosen. Two entries have scope: '
        '<b>signal cloth is a material, not a value</b> — each Role takes one step within it, so a party column '
        'reads as one channel rather than as three blues. <b>Ember and ember coral are one family in two jobs</b> — ember is the interface\'s '
        'warning, coral is Embermaw\'s own body, and they never appear in the same element.</div>'
    )
    card("colors-materials.html", "Colors", "Materials", "The locked table · 8 materials, what each carries", body, width=600)

    subtitles = {
        "glass": "#62D2E6 · seams, focus, Quick timing · 9 steps",
        "gold": "#C8A344 · lockwork, controls, Slow timing · 9 steps",
        "steel": "#1B2434 · panels and frames · 7 steps",
        "coral": "#E0703B · the Boss's own body · 8 steps",
        "ember": "#D9482F · damage taken, irreversible · 6 steps",
        "ceramic": "#E4E8EE · read-outs and the console · 6 steps",
        "cloth": "#2F5680 · one step per Role · 6 steps",
    }
    # Cloth is the one ramp whose steps are assigned rather than picked: the
    # party frames read a Role off the seat's deck and take its step.
    roles = "".join(
        f'<div style="display:flex;align-items:center;gap:10px">'
        f'<span class="ds-chipbox" style="width:26px;height:16px;background:var(--cloth-{step})"></span>'
        f'<span class="ds-mono" style="width:96px">--cloth-{step}</span>'
        f'<span class="ds-name" style="width:70px">{role}</span>'
        f'<span class="ds-note" style="flex:1">{note}</span></div>'
        for step, role, note in [
            (500, "Tank", "The deepest step — the Role that stands in front."),
            (400, "Damage", "Two Damage seats share this step. They are one Role, and the channel names Roles."),
            (300, "Healer", "The lit step, where the Role that answers damage is easiest to find in a column."),
        ]
    )
    cloth_extra = (
        '<div class="ds-lbl" style="margin-top:6px">The Role assignment</div>'
        f'<div class="ds-stack">{roles}</div>'
        '<div class="ds-note">This ramp used to be described as per-Hero, with these six steps standing in for '
        'Shield Wall\'s. The party frames settled it the other way: <b>a frame wears its Role\'s step</b>, read off '
        'the Keyword its seat\'s whole deck agrees on. Per-Hero could not survive a column — two Heroes of the same '
        'Role in two different blues says they differ in something, and they do not.</div>'
        '<div class="ds-note"><b>Role is the quietest thing a frame can say, and it yields.</b> Living gold takes the '
        'accent for the one frame the player can operate, ember for a body on the floor, ember coral for the Boss\'s '
        'attention — so cloth is what shows when nothing is happening to that Hero, which is most of the time.</div>'
    )
    for material, stem, carries, ramp, anchor in T.PALETTE:
        if stem in subtitles:
            ramp_card(material, stem, carries, ramp, anchor, subtitles[stem],
                      cloth_extra if stem == "cloth" else "")

    aliases = "".join(
        f'<tr><td style="padding:4px 14px 4px 0" class="ds-name">{name}</td>'
        f'<td style="padding:4px 14px 4px 0" class="ds-mono">{value}</td>'
        f'<td style="padding:4px 0" class="ds-note">{note}</td></tr>'
        for name, value, note in T.SEMANTIC
    )
    body = (
        '<div class="ds-lbl">Semantic aliases</div>'
        f'<table style="border-collapse:collapse;width:100%">{aliases}</table>'
        '<div class="ds-note">What the chrome reaches for by name. <b>--fg-quiet</b> is worth its own note: it is set '
        'to the dimmest step that still clears 4.5:1 on the brightest ground it sits on, which makes it lighter '
        'than the zinc it replaced. The step before it was failing at 3.09:1 and nobody could see it — Tailwind\'s '
        'own ramps compute to oklch(), which the contrast probe could not read, so it skipped every element '
        'wearing one.</div>'
    )
    card("colors-semantic.html", "Colors", "Semantic aliases", "ground · surface · plate · fg · focus", body, width=600)


# --- Type and spacing ------------------------------------------------------
def type_cards():
    rows = "".join(
        f'<div style="display:flex;align-items:baseline;gap:14px">'
        f'<span class="ds-mono" style="width:96px;flex-shrink:0">--type-{role}</span>'
        f'<span class="ds-mono" style="width:34px;flex-shrink:0">{px}px</span>'
        f'<span style="font-size:{px}px;font-weight:700;color:var(--ceramic-200);width:120px;flex-shrink:0">Riposte</span>'
        f'<span class="ds-note" style="flex:1">{note} <b>{uses} uses</b></span></div>'
        for role, px, uses, note in T.TYPE
    )
    body = (
        f'<div class="ds-stack">{rows}</div>'
        '<div class="ds-note">Ratified at seven steps (D-067) by transcribing what shipped and then narrowing it, '
        'which is how the palette was settled too. Nine steps had accumulated under the interface direction\'s '
        'silence; both singletons lived in the How to Play guide, so <b>8px folded into micro</b> and '
        '<b>16px up to title</b> — folding it down to body instead would have left the guide\'s heading the '
        'same size as its own body text.</div>'
        '<div class="ds-note"><b>The 9/10/11 cluster is deliberate and is not a candidate for merging.</b> Three '
        'sizes within three pixels looks like drift and is not: 9px is the demoted register, 10px the counted '
        'register, 11px the named register, each applied consistently. Collapsing them would be a redesign '
        'wearing a cleanup\'s clothes. An ESLint rule refuses a new arbitrary '
        '<span class="ds-mono">text-[Npx]</span> outside the seven — this line already failed on documentation '
        'alone, which is why the padding rule needed a browser check too.</div>'
    )
    card("type-scale.html", "Typography", "Scale", "7 steps, 9–24px · ratified D-067", body, width=620)

    weights = "".join(
        f'<div style="display:flex;align-items:baseline;gap:14px">'
        f'<span class="ds-mono" style="width:110px;flex-shrink:0">--weight-{role}</span>'
        f'<span style="font-size:15px;font-weight:{w};color:var(--ceramic-200);width:130px;flex-shrink:0">Sweeping Blow</span>'
        f'<span class="ds-note" style="flex:1">{note} · <b>{uses} uses</b></span></div>'
        for role, w, uses, note in T.TYPE_WEIGHTS
    )
    tracking = "".join(
        f'<div style="display:flex;align-items:baseline;gap:14px">'
        f'<span class="ds-mono" style="width:110px;flex-shrink:0">--tracking-{role}</span>'
        f'<span class="ds-mono" style="width:56px;flex-shrink:0">{value}</span>'
        f'<span style="font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:{value};'
        f'color:var(--ceramic-200);width:130px;flex-shrink:0">Quick</span>'
        f'<span class="ds-note" style="flex:1">{note}</span></div>'
        for role, value, note in T.TYPE_TRACKING
    )
    body = (
        '<div class="ds-lbl">Weight</div>'
        f'<div class="ds-stack">{weights}</div>'
        '<div class="ds-lbl" style="margin-top:6px">Tracking</div>'
        f'<div class="ds-stack">{tracking}</div>'
        '<div class="ds-note">There is no light or regular weight in the interface: at 9–12px on a dark ground '
        'nothing under 600 survives. <b>Black is rationed</b> — it appears only on words sitting on a lit '
        'face, where the ink is the face\'s own 950 step.</div>'
    )
    card("type-weight.html", "Typography", "Weight & tracking", "3 weights · 3 tracking steps · no regular", body, width=620)


def spacing_cards():
    items = "".join(
        f'<div class="ds-swatch" style="align-items:center"><div style="width:22px;height:{px}px;'
        f'background:var(--gold-500);border-radius:2px"></div>'
        f'<div class="ds-mono">{step} · {px}</div></div>'
        for step, px in T.SPACING
    )
    body = (
        f'<div class="ds-grid" style="align-items:flex-end">{items}</div>'
        '<div class="ds-note">Tailwind\'s default scale is the system (D-067), and deliberately not narrowed. '
        'Unlike typography it shows no evidence of harm — no truncation, no collision, no contradiction — and '
        'a rule with no defect behind it is ceremony. What did bite was the escape hatch, so arbitrary '
        '<span class="ds-mono">gap-[Npx]</span> is refused by the same lint rule that guards the type ramp. Use a '
        'scale step, or change the design.</div>'
    )
    card("spacing-scale.html", "Spacing", "Scale", "Tailwind default · the escape hatch is refused", body)

    radii = "".join(
        f'<div class="ds-swatch"><div class="ds-chipbox" style="background:var(--steel-800);border-radius:{value}"></div>'
        f'<div class="ds-name">{name}</div><div class="ds-mono">{value}</div>'
        f'<div class="ds-note" style="max-width:120px">{note}</div></div>'
        for name, value, note in T.RADII
    )
    body = (
        '<div class="ds-lbl">Radii</div>'
        f'<div class="ds-grid">{radii}</div>'
        '<div class="ds-note"><b>The default is 0, and that is a rule rather than an omission.</b> A plate\'s '
        'silhouette is its rake; a rounded corner on one would blunt the cut that carries its accent. Radii '
        'appear only on things that are not plates — gauge tracks, the class-resource bar, timing dots.</div>'
    )
    card("spacing-radii.html", "Spacing", "Radii", "0 by default · the rake is the silhouette", body)


# --- Plate cards -----------------------------------------------------------
def plate_cards():
    body = (
        '<div class="ds-lbl">Anatomy</div>'
        '<div class="ds-demo"><div class="plate p-xl f-steel a-gold" style="height:112px;display:flex;'
        'flex-direction:column;justify-content:center;gap:6px">'
        '<div style="font-size:12px;font-weight:700;color:var(--ceramic-200)">Content sits above both layers</div>'
        '<div class="ds-note" style="font-size:10px">::before paints the face and its 1px edge. '
        '::after paints the 3px leading accent.</div></div></div>'
        '<div class="ds-note">Every surface in the chrome is a parallelogram <b>raked 8° from vertical</b>, with the '
        'top-left corner notched out of the silhouette and the leading edge carrying an accent that runs the '
        'full cut. The rake is drawn on a <b>::before</b> layer with <b>clip-path</b> rather than by clipping the '
        'element, for two reasons that both matter: a clipped element loses its focus ring and shadow — and the '
        'accessibility contract requires a visible ring on every control — and it loses its border on the two '
        'cut edges.</div>'
        '<div class="ds-note"><b>offset = height × tan(8°)</b>. Derived, never chosen: a plate much taller than its '
        'size class simply wears a shallower rake, which is why the offset is the cut\'s real depth rather than '
        'an angle.</div>'
    )
    card("plate-anatomy.html", "Plates", "Anatomy", "8° rake · notched corner · derived offset", body)

    rows = "".join(
        f'<div style="display:flex;align-items:center;gap:14px">'
        f'<div class="plate p-{cls} f-steel a-gold" style="width:180px;height:52px;display:flex;'
        f'align-items:center;font-size:11px;font-weight:600">wb-plate-{cls}</div>'
        f'<div class="ds-note" style="flex:1"><b>off {off}px · notch {notch}px · gutter {gutter}px</b><br>{use} — {note}</div></div>'
        for cls, off, notch, gutter, use, note in T.PLATE_SIZES
    )
    body = f'<div class="ds-lbl">Seven sizes</div><div class="ds-stack">{rows}</div>'
    card("plate-sizes.html", "Plates", "Sizes", "7 classes · offset = height × tan(8°)", body, width=620)

    body = (
        '<div class="ds-lbl">The one padding rule</div>'
        '<div class="ds-mono" style="background:var(--steel-950);border:1px solid var(--steel-800);border-radius:6px;'
        'padding:12px 14px;font-size:11px;line-height:1.7;color:var(--glass-200)">'
        'padding-inline: calc(var(--wb-inset) + var(--wb-gutter));</div>'
        '<div class="ds-note"><b>--wb-inset</b> is how deep the cut reaches <i>this plate\'s content</i>. The leading '
        'edge is furthest in at the top and reaches zero at the bottom; the trailing edge does the reverse. So '
        'content spanning the plate meets the full offset, and content held to the middle band meets half of it '
        '(<b>wb-plate-centered</b>). <b>--wb-gutter</b> is the breathing room past the cut, and it is the only '
        'figure in the system tuned by eye.</div>'
        '<div class="ds-note">Nothing else sets padding-inline. A plate that wants width back lowers its gutter or '
        'declares where its content sits — it never ducks under its own cut. One exception, '
        '<b>wb-gutter-raked</b>, is for a plate carrying a text column: a raked box read as a column is a wedge, '
        'so it measures each side at the corner that side is worst at and adds the notch back on top.</div>'
        '<div class="ds-note"><b>A browser check holds every visible plate to padding ≥ --wb-inset</b>, so a new '
        'size cannot ship with content sitting in its own cut. This rule replaced seven hand-set values, a '
        'per-caller utility, and two inline styles no class could beat.</div>'
    )
    card("plate-padding.html", "Plates", "Padding rule", "One derived rule · guarded in the browser", body)

    faces = "".join(
        f'<div class="ds-swatch"><div class="plate p-md {"f-" + name} a-none" style="width:112px;height:48px;'
        f'display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:700;'
        f'letter-spacing:.08em;text-transform:uppercase;color:{ink}">{name}</div>'
        f'<div class="ds-note" style="max-width:112px">{use}</div></div>'
        for name, face, edge, ink, use in T.PLATE_FACES
    )
    body = f'<div class="ds-lbl">Six faces</div><div class="ds-grid">{faces}</div>'
    card("plate-faces.html", "Plates", "Faces", "steel · dim · ceramic · gold · coral · glass", body, width=600)

    accents = "".join(
        f'<div style="display:flex;align-items:center;gap:14px">'
        f'<div class="plate p-md f-steel {"a-" + name}" style="width:150px;height:48px;display:flex;'
        f'align-items:center;font-size:10px;color:var(--steel-400)">a-{name}</div>'
        f'<div class="ds-note" style="flex:1">{use}</div></div>'
        for name, value, use in T.PLATE_ACCENTS
    )
    body = (
        '<div class="ds-lbl">The status channel</div>'
        f'<div class="ds-stack">{accents}</div>'
        '<div class="ds-note">The accent runs <b>parallel to the cut, along that edge\'s full length</b> — it is '
        'drawn from the same offset variable as the face, not with a fixed-degree skew. A skew travels '
        'height × tan(8°), which matches the face only on a plate the height its size class assumed; on a tall '
        'modal it ran 70px inward and cut across the content while the face\'s own edge stayed 16px in.</div>'
    )
    card("plate-accents.html", "Plates", "Accents", "The status channel · 5 values", body, width=600)


# --- Component cards -------------------------------------------------------
def component_cards():
    states = [
        ("Empty", canvas.slot(None) + canvas.slot(None)),
        ("Loaded", canvas.slot("Iron Guard", 3, 0, "loaded", "quick", ("guard",)) + canvas.slot("Steady Strike", 2, 0, "loaded", "quick", ())),
        ("Charged", canvas.slot("Iron Guard", 3, 2, "charged", "quick", ("guard",)) + canvas.slot("Steady Strike", 2, 1, "charged", "quick", ())),
        ("Full", canvas.slot("Iron Guard", 3, 3, "full", "quick", ("guard",)) + canvas.slot("Steady Strike", 2, 2, "full", "quick", ())),
        ("Fired", canvas.slot("Iron Guard", 3, 3, "fired", "quick", ("guard",)) + canvas.slot("Steady Strike", 2, 2, "fired", "quick", ())),
        ("Out of window", canvas.slot("Fortify", 2, 2, "full", "slow", ("guard",), True) + canvas.slot("Quench", 2, 1, "charged", "slow", (), True)),
    ]
    rows = "".join(
        f'<div><div class="ds-lbl" style="margin-bottom:6px">{label}</div>'
        f'<div style="width:390px;background:var(--surface)">{canvas.action_bar(s)}</div></div>'
        for label, s in states
    )
    body = (
        f'<div class="ds-stack">{rows}</div>'
        '<div class="ds-note">State lives in two channels at once. The <b>leading-edge accent</b> is the status '
        'channel every plate shares. The <b>lock head</b> is the glance-distance signal: its ward ring is broken '
        'while charging and closed at full stack with a second faint ring outside it — a ring closing is a shape '
        'change, so it reads in peripheral vision and without colour. The tumblers say it a second way: separate '
        'raked pins with gaps while charging, and when the last one seats the gaps close and they read as one '
        'continuous bar.</div>'
        '<div class="ds-note"><b>Full and Fired share a complete Charge Stack and mean opposite things</b>, so they '
        'cannot share a picture. Fired reopens the ring, dulls the head and draws one runeglass strike across '
        'it. An out-of-window Slot drops to the dim face before Full is consulted: Full\'s gold says “can fire”, '
        'which is the one claim it must not make.</div>'
    )
    card("components-slot.html", "Components", "Action Bar Slot", "Empty · Loaded · Charged · Full · Fired · Out of window", body, width=440)

    frames = [
        ("Unearned", canvas.hero_frame(health=34, armor=0, charges=0, cap=2, deck=16, discard=0)),
        ("Banked", canvas.hero_frame(health=31, armor=4, charges=1, cap=2, deck=13, discard=3)),
        ("Ready — the Signature button mounts", canvas.hero_frame(health=28, armor=4, charges=1, cap=2, deck=11, discard=5, ready=True)),
        ("Full bank, with the Status Icon tray", canvas.hero_frame(
            health=24, armor=2, charges=2, cap=2, deck=9, discard=7, ready=True,
            counters=(("fortified", 1, 0, 0), ("seared", 2, 1, 3)))),
    ]
    rows = "".join(
        f'<div><div class="ds-lbl" style="margin-bottom:6px">{label}</div>'
        f'<div class="ds-demo" style="position:relative;width:390px;height:84px;overflow:hidden;padding:0">{f}</div></div>'
        for label, f in frames
    )
    body = (
        f'<div class="ds-stack">{rows}</div>'
        '<div class="ds-note">A left-justified vertical stack: <b>name</b>, <b>health with the Armor overlay</b>, '
        '<b>the class resource where an MMO puts mana</b>, then <b>the deck and discard counts</b>. '
        '<b>One hold target, not four</b> — every button owes a 44px tap target, so four interactive rows would '
        'be 176px of chrome over a board with 95px to spare.</div>'
        '<div class="ds-note"><b>The bar is read; the button is pressed.</b> The resource bar is segmented because '
        'a Charge is counted rather than continuous, and unlabelled because its position is the label. The '
        'Signature button exists only while the Signature can fire — safe precisely because the bar carries '
        'permanence, and refused before the bar existed.</div>'
        '<div class="ds-note">The <b>Status Icon tray</b> beside the frame is the same 44pt rule answered a second '
        'time, and it has its own card. It replaced a named Counter chip in D-088: <b>SEARED</b> alone took the '
        'width two Counters need.</div>'
    )
    card("components-hero-frame.html", "Components", "Hero Frame", "Unearned · Banked · Ready · Full bank", body, width=440)

    w = "90.5px"
    faces = [
        ("Card face — Loadout", "".join([
            canvas.card_face("Iron Guard", "quick", 3, "guard", w),
            canvas.card_face("Sweeping Blow", "quick", 2, "attack", w),
            canvas.card_face("Fortify", "slow", 2, "guard", w),
            canvas.card_face("Steady Strike", "quick", 2, "attack", w, selected=True)]), ""),
        ("Keyword face — Quick and Slow", "".join([
            canvas.keyword_face("Iron Guard", ["guard", "tank"], {"guard", "tank"}, w),
            canvas.keyword_face("Sweeping Blow", ["attack", "board"], {"attack"}, w),
            canvas.keyword_face("Fortify", ["guard", "growth"], {"guard"}, w),
            canvas.keyword_face("Quench", ["tempo", "support"], set(), w)]), ""),
        ("Stamina face — a move lined up", "".join([
            canvas.stamina_face("Iron Guard", False, w), canvas.stamina_face("Sweeping Blow", True, w),
            canvas.stamina_face("Fortify", False, w), canvas.stamina_face("Quench", False, w)]), " offering"),
    ]
    rows = "".join(
        f'<div><div class="ds-lbl" style="margin-bottom:6px">{label}</div>'
        f'<div class="hand{cls}" style="width:390px">{h}</div></div>'
        for label, h, cls in faces
    )
    body = (
        f'<div class="ds-stack">{rows}</div>'
        '<div class="ds-note">What a Compact Card shows is the face the current gesture calls for. The '
        '<b>card face</b> describes it as a Top Card, which is what Loadout is choosing. The <b>keyword face</b> '
        'drops the speed word and the Charge pips — both describe a Top Card, and a card being tucked adds one '
        'Charge whatever its own speed says — and promotes the Hero\'s marks, gold on the ones a loaded Top Card '
        'would pay off for. The <b>Stamina face</b> makes the Hand a stack of interchangeable coins, because '
        'looking like anything else would suggest the choice of which to spend matters more than it does.</div>'
        '<div class="ds-note">A card keeps one width — its share of a full Hand — whether five remain or one. Cards '
        'that stretched to fill the row stopped reading as cards.</div>'
    )
    card("components-hand-card.html", "Components", "Compact Card", "Card · Keyword · Stamina faces", body, width=440)

    tracks = "".join(
        f'<div><div class="ds-lbl" style="margin-bottom:6px">{label}</div>'
        f'<div style="width:390px;background:var(--surface)">{canvas.phase_band(phase, r, e, f)}</div></div>'
        for phase, label, r, e, f in [
            ("loadout", "Loadout", 1, 0, 0.25), ("instant", "Boss Instant", 2, 0, 0.5),
            ("quick", "Quick Window", 3, 1, 0.0), ("incoming", "Boss Incoming", 5, 2, 0.0),
            ("slow", "Slow Window", 7, 4, 0.0)]
    )
    body = (
        f'<div class="ds-stack">{tracks}</div>'
        '<div class="ds-note">Five marks, one per window, each wearing its owner\'s tone at rest and its wedge — '
        '<b>the Boss\'s windows point down at the board, yours point up</b> — so the Round\'s shape reads before '
        'any window opens. Loadout carries no wedge: nothing fires there, and the blank is the signal.</div>'
        '<div class="ds-note">The live window is not a sixth tint but the row\'s <b>one lit chip</b>: a raked plate '
        'in the owner\'s material carrying the window\'s word. One word always fits where five never did, and a '
        'lit plate is visible from the board the way an 18px hue shift was not.</div>'
    )
    card("components-phase-track.html", "Components", "Round track", "5 windows · owner wedges · one lit chip", body, width=440)

    body = (
        '<div class="ds-lbl">Escalation — the encounter\'s only clock</div>'
        f'<div class="ds-demo" style="width:390px">{canvas.escalation(0, 0.5)}{canvas.escalation(2, 0)}{canvas.escalation(4, 0)}</div>'
        '<div class="ds-note">It carries <b>no label</b>: a word costs more room than the reading it buys, and the '
        'reading is in the shape. The last band — the one that ends the fight — is washed in at the far end '
        'before the clock ever reaches it, and a <b>fuse</b> burns through the first band while the automatic '
        'ticks are still dormant, so a clock that cannot move yet does not read as one that has stopped.</div>'
        '<div class="ds-note">The bar is divided at the band boundaries rather than left to slide: <b>a bar that '
        'only slides is a percentage</b>, and Escalation moves in bands that each land once.</div>'
        '<div class="ds-lbl" style="margin-top:6px">The shared gauge language</div>'
        '<div class="ds-note">A dark track, a fill measured from the left, and the number overlaid with a shadow so '
        'it stays crisp where it straddles the fill edge. <b>Armor rides the health bar in the same currency</b> — '
        'when the stack exceeds max health the track\'s scale stretches so both fills stay inside it.</div>'
    )
    card("components-gauges.html", "Components", "Gauges", "Escalation clock · health + Armor · class resource", body, width=440)

    beat = ('<button class="plate p-md p-raked f-steel a-ember beat">'
            '<span class="beat-head"><span class="beat-track">Boss · Instant</span>'
            '<span class="beat-verb">Resolve ▸</span></span>'
            '<span class="beat-title">Close the Gap</span>'
            '<span class="beat-stats"><span class="beat-stat"><b>Advances</b> 1 hex</span></span>'
            '<span class="beat-text">Embermaw advances one hex toward the guardian. Distance is not an answer for long.</span>'
            '<span class="beat-tags">Position</span></button>')
    demand = ('<div class="plate p-sm p-raked f-steel a-ember demand" style="--gutter-block:6px">'
              '<span class="demand-word">Standing</span>'
              '<span style="font-size:11px;font-weight:700;color:var(--coral-100)">Brood Call</span>'
              '<span style="font-size:10px;font-weight:600;color:var(--ember-300)">Unanswered</span></div>')
    toast = '<div class="plate p-sm f-steel a-ember toast">The Signature charges only through its standing clause.</div>'
    body = (
        f'<div class="ds-stack" style="width:374px">{beat}{demand}{toast}</div>'
        '<div class="ds-note">Every floating surface lands in one of three zones, and the zones are flex siblings '
        'of one column — so no two can share a pixel, and a bar appearing or leaving <b>never resizes the board '
        'mid-Encounter</b>. Guidance floats over the top hexes; the stage takes the middle for one announcement '
        'at a time; the dock hugs the Action Bar, and its floor is the Hero Frame\'s top edge.</div>'
        '<div class="ds-note">The Beat Card\'s <b>accent</b> breathes, not its face. A face dipping to 55% shows the '
        'board straight through a card carrying rules text — and nothing flags it, because the text\'s own '
        'opacity never moves, so a contrast check on declared colours passes while the composited pixels '
        'fail.</div>'
    )
    card("components-dock.html", "Components", "Dock", "Beat Card · Standing Demand · toasts", body, width=440)

    rails = (
        '<div class="ds-grid" style="align-items:center">'
        '<button class="plate p-lg p-centered f-steel a-glass rail" style="width:58px;color:var(--glass-200)">'
        + canvas.ICON["undo"]("i28") + '</button>'
        '<button class="plate p-lg p-centered f-dim a-none rail" style="width:58px;color:var(--steel-500)">'
        + canvas.ICON["undo"]("i28") + '</button>'
        '<button class="plate p-lg p-centered f-gold a-gold rail" style="width:58px;color:var(--gold-950)">'
        + canvas.ICON["advance"]("i28") + '</button>'
        '<button class="plate p-lg p-centered f-gold a-gold rail" style="width:58px;color:var(--gold-950)">'
        + canvas.ICON["play"]("i28") + '</button>'
        '<button class="plate p-lg p-centered f-gold a-gold rail" style="width:58px;color:var(--gold-950)">'
        + canvas.ICON["restart"]("i28") + '</button>'
        '<button class="plate p-sm f-gold a-gold sig" style="margin-left:0">'
        '<span class="sig-name">Riposte</span><span class="sig-verb">Fire</span></button></div>'
    )
    body = (
        f'{rails}'
        '<div class="ds-note">Left to right: <b>undo armed</b>, <b>undo inert</b>, <b>next</b>, <b>continue</b>, '
        '<b>restart</b>, the <b>Signature button</b>. Undo is steel and the advance rail '
        'is gold: both are always present, and the eye has to tell the move that advances the fight from the one '
        'that walks it back without reading either.</div>'
        '<div class="ds-note">The two forward marks are deliberately different shapes. <b>A bare triangle plays</b> '
        'the next beat of a Boss Row; <b>a triangle against a bar</b> runs to the end of the window and stops. '
        'Both rails hold their mark to the plate\'s middle, so they take the centred inset — the cut is half as '
        'deep there, and the glyph keeps the room the full rake would have spent.</div>'
        '<div class="ds-note"><b>An inert rail is dimmed, not absent.</b> At the step below, the mark scored about '
        '2.2:1 and read as an empty plate, which makes the bar look like it lost a control rather than like this '
        'one is waiting.</div>'
    )
    card("components-rails.html", "Components", "Rails & buttons", "Undo · next · continue · Signature", body, width=440)


def party_cards():
    states = [
        ("At rest — Role on the accent, one ally carrying the Boss's attention", [
            dict(name="Maren", role="healer", health=22, max_health=26, charges=1, cap=2),
            dict(name="Roan Kesh", role="damage", health=19, max_health=24, armor=3, threat=True),
        ]),
        ("Downed — hatched track, ember accent, the bank gone", [
            dict(name="Maren", role="healer", health=0, max_health=26, status="downed"),
            dict(name="Roan Kesh", role="damage", health=19, max_health=24, armor=3),
        ]),
        ("Revivable — the frame is the button, and prints its price", [
            dict(name="Maren", role="healer", health=0, max_health=26, status="downed", revivable=True),
            dict(name="Roan Kesh", role="damage", health=19, max_health=24, armor=3),
        ]),
        ("Incapacitated — the rescue window closed", [
            dict(name="Maren", role="healer", health=0, max_health=26, status="incapacitated"),
            dict(name="Roan Kesh", role="damage", health=11, max_health=24, threat=True),
        ]),
    ]
    rows = "".join(
        f'<div><div class="ds-lbl" style="margin-bottom:6px">{label}</div>'
        f'<div class="ds-demo" style="position:relative;width:390px;height:168px;overflow:hidden;padding:0">'
        f'{canvas.party_frames(frames)}'
        f'{canvas.hero_frame(health=31, armor=4, charges=1, cap=2, deck=11, discard=5)}</div></div>'
        for label, frames in states
    )
    body = (
        f'<div class="ds-stack">{rows}</div>'
        '<div class="ds-note">A left-edge column of readouts growing upward from the primary Hero\'s frame, over '
        'board pixels the melee party is standing near anyway — so <b>the board keeps 100% of its width</b>. Every '
        'frame is the primary frame\'s anatomy with the console removed: name, health with the Armor overlay, the '
        'Signature bank. No piles, no controls.</div>'
        '<div class="ds-note"><b>A frame at rest owes no tap target</b>, so the resting height is free to stay under '
        '44px. In the one moment a legal ally action exists — the primary Hero adjacent to a Downed ally with a card '
        'in hand — that frame alone becomes the button: its accent turns living gold, the bar names the price, and a '
        'tap parks the rescue the way a move parks. Otherwise the frame is <b>the switch</b>: one player pilots the '
        'Party, and a tap swaps the whole panel over a shared board with no camera movement. The column shows '
        'whoever the console does not, so the swap is symmetric.</div>'
        '<div class="ds-note"><b>Status outranks Role on the accent channel.</b> Role is the Signal cloth step and is '
        'what a frame wears with nothing more urgent to say; living gold overrides it for the one frame the player '
        'can operate, ember for a body on the floor, ember coral for the Boss\'s attention. <b>A Downed track is '
        'hatched, not empty</b> — an empty bar is a Hero at 0 health, which is a different claim.</div>'
    )
    card("components-party-frames.html", "Components", "Party frames",
         "At rest · Downed · Revivable · Incapacitated", body, width=440)


def status_card():
    marks = "".join(
        f'<div class="ds-swatch" style="align-items:center;width:84px">{canvas.status_icon(cid)}'
        f'<div class="ds-name">{cid}</div>'
        f'<div class="ds-mono">{canvas.STATUS_MARKS[cid][1]}</div></div>'
        for cid in ("seared", "heat", "sundered", "weakened", "fortified", "underwritten")
    )
    # A Counter id the mark table has never heard of, which is the point: it
    # falls back to the hollow steel rhombus rather than failing to draw.
    marks += (
        f'<div class="ds-swatch" style="align-items:center;width:84px">{canvas.status_icon("a-rule-authored-today")}'
        f'<div class="ds-name">unmarked</div><div class="ds-mono">steel</div></div>'
    )
    riders = "".join(
        f'<div class="ds-swatch" style="align-items:center;width:104px">{icon}'
        f'<div class="ds-note" style="max-width:104px;text-align:center">{note}</div></div>'
        for icon, note in [
            (canvas.status_icon("fortified"), "Single and permanent — <b>quiet</b>"),
            (canvas.status_icon("seared", 3), "Three held — the <b>count</b>, bottom-right"),
            (canvas.status_icon("sundered", 1, 1, 3), "One Round left — the <b>clock</b> across the foot"),
            (canvas.status_icon("heat", 2, 2, 3), "Both, and the count lifts clear"),
        ]
    )
    body = (
        '<div class="ds-lbl">The marks</div>'
        f'<div class="ds-grid">{marks}</div>'
        '<div class="ds-lbl" style="margin-top:6px">What rides the square</div>'
        f'<div class="ds-grid">{riders}</div>'
        '<div class="ds-lbl" style="margin-top:6px">The tray</div>'
        f'<div class="ds-demo" style="display:flex">{canvas.status_tray((("seared", 2, 1, 3), "fortified", ("underwritten", 1, 0, 0), "weakened"))}</div>'
        '<div class="ds-note">A Counter as a <b>raked square rather than a word</b> (D-088). The chip it replaced '
        'spelled its title across a 74px plate — <b>SEARED</b> beside the Hero Frame took the width two Counters '
        'need, and a third had nowhere to go on a 390pt surface. A square the size of a glyph is what an MMO\'s buff '
        'tray is, and it works for the same reason: the player learns one mark per rule and then reads the row at a '
        'glance, where a row of words has to be read left to right.</div>'
        '<div class="ds-note">The square is a <b>plate like every other surface</b>, so the rake and the leading-edge '
        'accent are not re-derived: <b>the accent band is the material channel</b>, and the glyph is cut in the same '
        'material. The glyphs are filled where the Compact Card\'s Keyword marks are open strokes, so the two are '
        'never confused at 16 pixels.</div>'
        '<div class="ds-note"><b>The name is not lost — it is one hold away</b>, with the authored rules text, the '
        'count and the rounds. And a Counter this table has never heard of still reads as one: it falls back to the '
        'hollow steel rhombus, which claims nothing else, so a freshly authored rule is visible on the frame the day '
        'it lands.</div>'
        '<div class="ds-note"><b>One control, not one per Counter.</b> Four Counters as four targets is 176px of '
        'chrome beside a 208px frame; the squares pack at the density they were drawn at and the tray as a whole '
        'takes the press, so the block padding is what buys the 44pt target.</div>'
    )
    card("components-status-icons.html", "Components", "Status Icons",
         "6 marks + the fallback · count · round clock · the tray", body, width=560)


def motion_card():
    rows = "".join(
        f'<div style="display:flex;align-items:baseline;gap:12px">'
        f'<span class="ds-mono" style="width:132px;flex-shrink:0">{name}</span>'
        f'<span class="ds-mono" style="width:52px;flex-shrink:0">{dur}</span>'
        f'<span class="ds-name" style="width:44px;flex-shrink:0;color:{"var(--gold-400)" if kind == "loop" else "var(--glass-300)"}">{kind}</span>'
        f'<span class="ds-note" style="flex:1">{note}</span></div>'
        for name, dur, ease, kind, note in T.MOTION
    )
    body = (
        f'<div class="ds-stack">{rows}</div>'
        '<div class="ds-note">The house rule: <b>motion that carries state fires once; only ambient motion may '
        'loop.</b> A Full Slot can persist for Rounds, and anything that breathes that long becomes furniture '
        'the eye edits out — the failure that got an earlier idle pulse deleted.</div>'
        '<div class="ds-note">A second rule follows from contrast: <b>never breathe a layer that has text on it.</b> '
        'The face and accent live on ::before and ::after precisely so a plate can pulse without its label '
        'dipping under its contrast floor. Everything freezes under <span class="ds-mono">prefers-reduced-motion</span>.</div>'
    )
    card("motion-set.html", "Motion", "The set", "7 animations · only ambient motion loops", body, width=620)


# --- Manifest --------------------------------------------------------------
def manifest(namespace):
    tokens = []
    for name, value in T.color_vars():
        tokens.append({"name": name, "value": value, "kind": "color", "definedIn": "colors_and_type.css"})
    for name, value, _note in T.SEMANTIC:
        kind = "font" if name.startswith("--fg") else "color"
        tokens.append({"name": name, "value": value, "kind": kind, "definedIn": "colors_and_type.css"})
    tokens.append({"name": "--font-sans", "value": T.FONT_STACK, "kind": "font", "definedIn": "colors_and_type.css"})
    tokens.append({"name": "--font-mono", "value": T.MONO_STACK, "kind": "font", "definedIn": "colors_and_type.css"})
    for role, px, _uses, _note in T.TYPE:
        tokens.append({"name": f"--type-{role}", "value": f"{px}px", "kind": "font", "definedIn": "colors_and_type.css"})
    for role, weight, _uses, _note in T.TYPE_WEIGHTS:
        tokens.append({"name": f"--weight-{role}", "value": str(weight), "kind": "font", "definedIn": "colors_and_type.css"})
    for role, value, _note in T.TYPE_TRACKING:
        tokens.append({"name": f"--tracking-{role}", "value": value, "kind": "font", "definedIn": "colors_and_type.css"})
    for step, px in T.SPACING:
        tokens.append({"name": f"--space-{str(step).replace('.', '_')}", "value": f"{px}px", "kind": "spacing", "definedIn": "colors_and_type.css"})
    for name, value, _note in T.RADII:
        tokens.append({"name": f"--radius-{name}", "value": value, "kind": "radius", "definedIn": "colors_and_type.css"})
    return {
        "namespace": namespace,
        "components": [],
        "startingPoints": [],
        "cards": CARDS,
        "templates": [],
        "hasThumbnailHtml": False,
        "globalCssPaths": ["colors_and_type.css"],
        "tokens": tokens,
        "themes": [],
        "fonts": [],
        "brandFonts": [{"family": "System sans", "status": "ok", "tokens": ["--font-sans"], "path": "colors_and_type.css"}],
        "source": "spa",
    }


def build(namespace="OathcraftDesignSystem"):
    colour_cards()
    type_cards()
    spacing_cards()
    plate_cards()
    component_cards()
    party_cards()
    status_card()
    motion_card()
    write("colors_and_type.css", stylesheet())
    write("_ds_manifest.json", json.dumps(manifest(namespace), indent=2) + "\n")
    print(f"wrote {len(CARDS)} cards + colors_and_type.css + _ds_manifest.json")
    return CARDS


if __name__ == "__main__":
    build(sys.argv[1] if len(sys.argv) > 1 else "OathcraftDesignSystem")
